#ifndef DASH_PARSER_EVENTS_H_
#define DASH_PARSER_EVENTS_H_

enum DASH_PARSER_RESULT {
    DASH_PARSER_RESULT_OK,
    DASH_PARSER_RESULT_COMMON_ERROR,
    DASH_PARSER_RESULT_BAD_MPD,
};

#endif  // !DASH_PARSER_EVENTS_H_